name: deploy frontend application
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: prepare the docker-compose run
        run: |
              ls -l
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sktp03/final_project:latest
      -
        name: prepare the docker-compose run
        run: |
              mkdir final_project
              cp docker-compose.yml final_project/docker-compose.yml
              cd final_project
              docker-compose -H ${{ secrets.HOST_SERVER  }} down
              docker-compose -H ${{ secrets.HOST_SERVER  }} pull
              docker-compose -H ${{ secrets.HOST_SERVER  }} up -d